/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick */

#ifndef _Included_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
#define _Included_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    initJoystick0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_initJoystick0
  (JNIEnv *, jclass, jint);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    getOptionButton0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_getOptionButton0
  (JNIEnv *, jclass, jint);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    getStartMode0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_getStartMode0
  (JNIEnv *, jclass);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    getEmergencyMode0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_getEmergencyMode0
  (JNIEnv *, jclass);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    getPitch0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_getPitch0
  (JNIEnv *, jclass);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    getYaw0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_getYaw0
  (JNIEnv *, jclass);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    getRoll0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_getRoll0
  (JNIEnv *, jclass);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    getHeight0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_getHeight0
  (JNIEnv *, jclass);

/*
 * Class:     nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick
 * Method:    shutdownJoystick0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nl_ru_ai_projects_parrot_dronecontrol_groundstation_SDLDroneJoystick_shutdownJoystick0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
