/*
    This file is part of the BioMAV project.

    The BioMAV project is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The BioMAV project is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with The BioMAV project. If not, see <http://www.gnu.org/licenses/>.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector */

#ifndef _Included_nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector
#define _Included_nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector
 * Method:    init0
 * Signature: (IIZDZZIIIZZ)V
 */
JNIEXPORT void JNICALL Java_nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector_init0
  (JNIEnv *, jclass, jint, jint, jboolean, jdouble, jboolean, jboolean, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector
 * Method:    setData
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector_setData
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector
 * Method:    getPolePositions
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector_getPolePositions
  (JNIEnv *, jclass);

/*
 * Class:     nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector
 * Method:    getPoleDistances
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_nl_ru_ai_projects_parrot_poledetection_CPPPoleDetector_getPoleDistances
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
